### PR TITLE
fix for #47

### PR DESCRIPTION
**Pull request by f11h**
added tenant id to CloudOfThingsPlatform initialization

### CODE REVIEW

**Comment by f11h** [comment]
see #47 for detailed information

**Comment by Andyck** [comment]
Thanks for improvement!
It works fine this way!

**Comment by rokkbert** [comment]
@f11h , could You please direct this pull request to the _develop_ branch? Then we'll be happy to merge it. https://github.com/blog/2224-change-the-base-branch-of-a-pull-request
We commit to _master_ only for new releases.

**Comment by f11h** [comment]
see #49

**Comment by rokkbert** [comment]
Cool, thanks.

**Pull request closed without merging**
